In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

## V1 Dataset

In [3]:
data = pd.read_csv('/Users/sohammandal/Developer/mlops-summer-2025/Data Versioning/athletes.csv')
data.head()

,athlete_id,name,region,team,affiliate,gender,age,height,weight,fran,...,snatch,deadlift,backsq,pullups,eat,train,background,experience,schedule,howlong
0,2554.0,Pj Ablang,South West,Double Edge,Double Edge CrossFit,Male,24.0,70.0,166.0,NaN,...,NaN,400.0,305.0,NaN,NaN,I workout mostly at a CrossFit Affiliate|I hav...,I played youth or high school level sports|I r...,I began CrossFit with a coach (e.g. at an affi...,I do multiple workouts in a day 2x a week|,4+ years|
1,3517.0,Derek Abdella,NaN,NaN,NaN,Male,42.0,70.0,190.0,NaN,...,NaN,NaN,NaN,NaN,NaN,I have a coach who determines my programming|I...,I played youth or high school level sports|,I began CrossFit with a coach (e.g. at an affi...,I do multiple workouts in a day 2x a week|,4+ years|
2,4691.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5164.0,Abo Brandon,Southern California,LAX CrossFit,LAX CrossFit,Male,40.0,67.0,NaN,211.0,...,200.0,375.0,325.0,25.0,I eat 1-3 full cheat meals per week|,I workout mostly at a CrossFit Affiliate|I hav...,I played youth or high school level sports|,I began CrossFit by trying it alone (without a...,I usually only do 1 workout a day|,4+ years|
4,5286.0,Bryce Abbey,NaN,NaN,NaN,Male,32.0,65.0,149.0,206.0,...,150.0,NaN,325.0,50.0,I eat quality foods but don't measure the amount|,I workout mostly at a CrossFit Affiliate|I inc...,I played college sports|,I began CrossFit by trying it alone (without a...,I usually only do 1 workout a day|I strictly s...,1-2 years|

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 423006 entries, 0 to 423005
Data columns (total 27 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   athlete_id  423003 non-null  float64
 1   name        331110 non-null  object
 2   region      251262 non-null  object
 3   team        155160 non-null  object
 4   affiliate   241916 non-null  object
 5   gender      331110 non-null  object
 6   age         331110 non-null  float64
 7   height      159869 non-null  float64
 8   weight      229890 non-null  float64
 9   fran        55426 non-null   float64
 10  helen       30279 non-null   float64
 11  grace       40745 non-null   float64
 12  filthy50    19359 non-null   float64
 13  fgonebad    29738 non-null   float64
 14  run400      22246 non-null   float64
 15  run5k       36097 non-null   float64
 16  candj       104435 non-null  float64
 17  snatch      97280 non-null   float64
 18  deadlift    115323 non-null  float64
 19  backsq      110517 non-null  float64
 20  pullups     50608 non-null   float64
 21  eat         93932 non-null   object
 22  train       105831 non-null  object
 23  background  98945 non-null   object
 24  experience  104936 non-null  object
 25  schedule    97875 non-null   object
 26  howlong     109206 non-null  object
dtypes: float64(16), object(11)
memory usage: 87.1+ MB

In [5]:
data["total_lift"] = data["deadlift"] + data["candj"] + data["snatch"] + data["backsq"]

train_df, test_df = train_test_split(data, test_size=0.2, random_state=42)

# Save splits
train_df.to_csv("v1_train.csv", index=False)
test_df.to_csv("v1_test.csv", index=False)

### V2 Dataset

In [7]:
data = pd.read_csv('/Users/sohammandal/Developer/mlops-summer-2025/Data Versioning/athletes.csv')
data.head()

,athlete_id,name,region,team,affiliate,gender,age,height,weight,fran,...,snatch,deadlift,backsq,pullups,eat,train,background,experience,schedule,howlong
0,2554.0,Pj Ablang,South West,Double Edge,Double Edge CrossFit,Male,24.0,70.0,166.0,NaN,...,NaN,400.0,305.0,NaN,NaN,I workout mostly at a CrossFit Affiliate|I hav...,I played youth or high school level sports|I r...,I began CrossFit with a coach (e.g. at an affi...,I do multiple workouts in a day 2x a week|,4+ years|
1,3517.0,Derek Abdella,NaN,NaN,NaN,Male,42.0,70.0,190.0,NaN,...,NaN,NaN,NaN,NaN,NaN,I have a coach who determines my programming|I...,I played youth or high school level sports|,I began CrossFit with a coach (e.g. at an affi...,I do multiple workouts in a day 2x a week|,4+ years|
2,4691.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5164.0,Abo Brandon,Southern California,LAX CrossFit,LAX CrossFit,Male,40.0,67.0,NaN,211.0,...,200.0,375.0,325.0,25.0,I eat 1-3 full cheat meals per week|,I workout mostly at a CrossFit Affiliate|I hav...,I played youth or high school level sports|,I began CrossFit by trying it alone (without a...,I usually only do 1 workout a day|,4+ years|
4,5286.0,Bryce Abbey,NaN,NaN,NaN,Male,32.0,65.0,149.0,206.0,...,150.0,NaN,325.0,50.0,I eat quality foods but don't measure the amount|,I workout mostly at a CrossFit Affiliate|I inc...,I played college sports|,I began CrossFit by trying it alone (without a...,I usually only do 1 workout a day|I strictly s...,1-2 years|

In [8]:
# Remove not relevant columns
data = data.dropna(subset=['region','age','weight','height','howlong','gender','eat', \
                            'train','background','experience','schedule','howlong', \
                            'deadlift','candj','snatch','backsq','experience',\
                            'background','schedule','howlong'])
data = data.drop(columns=['affiliate','team','name','athlete_id','fran','helen','grace',\
                            'filthy50','fgonebad','run400','run5k','pullups','train'])

# Remove Outliers

data = data[data['weight'] < 1500]
data = data[data['gender'] != '--']
data = data[data['age'] >= 18]
data = data[(data['height'] < 96) & (data['height'] > 48)]

data = data[
    ((data['gender'] == 'Male') & (data['deadlift'] > 0) & (data['deadlift'] <= 1105)) |
    ((data['gender'] == 'Female') & (data['deadlift'] > 0) & (data['deadlift'] <= 636))
]
data = data[(data['candj'] > 0) & (data['candj'] <= 395)]
data = data[(data['snatch'] > 0) & (data['snatch'] <= 496)]
data = data[(data['backsq'] > 0) & (data['backsq'] <= 1069)]

# Clean Survey Data

decline_dict = {'Decline to answer|': np.nan}
data = data.replace(decline_dict)
data = data.dropna(subset=['background','experience','schedule','howlong','eat'])

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30015 entries, 21 to 422961
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   region      30015 non-null  object
 1   gender      30015 non-null  object
 2   age         30015 non-null  float64
 3   height      30015 non-null  float64
 4   weight      30015 non-null  float64
 5   candj       30015 non-null  float64
 6   snatch      30015 non-null  float64
 7   deadlift    30015 non-null  float64
 8   backsq      30015 non-null  float64
 9   eat         30015 non-null  object
 10  background  30015 non-null  object
 11  experience  30015 non-null  object
 12  schedule    30015 non-null  object
 13  howlong     30015 non-null  object
dtypes: float64(7), object(7)
memory usage: 3.4+ MB

In [10]:
data["total_lift"] = data["deadlift"] + data["candj"] + data["snatch"] + data["backsq"]

train_df, test_df = train_test_split(data, test_size=0.2, random_state=42)

# Save splits
train_df.to_csv("v2_train.csv", index=False)
test_df.to_csv("v2_test.csv", index=False)